import { ChapterProgress, AdmissionExam, SubjectId, PaperId } from "../types";

export interface ChapterMetadata {
  id: string;
  subject: SubjectId;
  paper: PaperId;
  chapterNumber: number;
  nameBn: string;
  nameEn: string;
}

export const CHAPTER_METADATA: ChapterMetadata[] = [
  // ==================== PHYSICS 1ST PAPER ====================
  {
    id: 'phy-1-1',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: ভৌত জগত ও পরিমাপ',
    nameEn: 'Physical World and Measurement',
  },
  {
    id: 'phy-1-2',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: ভেক্টর',
    nameEn: 'Vectors',
  },
  {
    id: 'phy-1-3',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: গতিবিদ্যা',
    nameEn: 'Dynamics',
  },
  {
    id: 'phy-1-4',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: নিউটনীয় বলবিদ্যা',
    nameEn: 'Newtonian Mechanics',
  },
  {
    id: 'phy-1-5',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: কাজ, শক্তি ও ক্ষমতা',
    nameEn: 'Work, Energy and Power',
  },
  {
    id: 'phy-1-6',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: মহাকর্ষ ও অভিকর্ষ',
    nameEn: 'Gravitation and Gravity',
  },
  {
    id: 'phy-1-7',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: পদার্থের গাঠনিক ধর্ম',
    nameEn: 'Structural Properties of Matter',
  },
  {
    id: 'phy-1-8',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: পর্যায়বৃত্ত গতি',
    nameEn: 'Periodic Motion',
  },
  {
    id: 'phy-1-9',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: তরঙ্গ',
    nameEn: 'Waves',
  },
  {
    id: 'phy-1-10',
    subject: 'physics' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: আদর্শ গ্যাস ও গ্যাসের গতিতত্ত্ব',
    nameEn: 'Ideal Gas and Kinetic Theory of Gases',
  },
  // ==================== PHYSICS 2ND PAPER ====================
  {
    id: 'phy-2-1',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: তাপগতিবিদ্যা',
    nameEn: 'Thermodynamics',
  },
  {
    id: 'phy-2-2',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: স্থির তড়িৎ',
    nameEn: 'Static Electricity',
  },
  {
    id: 'phy-2-3',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: চল তড়িৎ',
    nameEn: 'Current Electricity',
  },
  {
    id: 'phy-2-4',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: তড়িৎ প্রবাহের চৌম্বক ক্রিয়া ও চুম্বকত্ব',
    nameEn: 'Magnetic Effects of Current & Magnetism',
  },
  {
    id: 'phy-2-5',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: তাড়িতচৌম্বকীয় আবেশ ও পরিবর্তী প্রবাহ',
    nameEn: 'Electromagnetic Induction & AC',
  },
  {
    id: 'phy-2-6',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: জ্যামিতিক আলোকবিজ্ঞান',
    nameEn: 'Geometrical Optics',
  },
  {
    id: 'phy-2-7',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: ভৌত আলোকবিজ্ঞান',
    nameEn: 'Physical Optics',
  },
  {
    id: 'phy-2-8',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: আধুনিক পদার্থবিজ্ঞানের সূচনা',
    nameEn: 'Introduction to Modern Physics',
  },
  {
    id: 'phy-2-9',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: পরমাণু মডেল ও নিউক্লিয়ার পদার্থবিজ্ঞান',
    nameEn: 'Atomic Model and Nuclear Physics',
  },
  {
    id: 'phy-2-10',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: সেমিকন্ডাক্টর ও ইলেকট্রনিক্স',
    nameEn: 'Semiconductors and Electronics',
  },
  {
    id: 'phy-2-11',
    subject: 'physics' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 11,
    nameBn: 'অধ্যায় ১১: জ্যোতির্বিজ্ঞান',
    nameEn: 'Astronomy',
  },
  // ==================== HIGHER_MATH 1ST PAPER ====================
  {
    id: 'math-1-1',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: ম্যাট্রিক্স ও নির্ণায়ক',
    nameEn: 'Matrices and Determinants',
  },
  {
    id: 'math-1-2',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: ভেক্টর',
    nameEn: 'Vectors (Math)',
  },
  {
    id: 'math-1-3',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: সরলরেখা',
    nameEn: 'Straight Lines',
  },
  {
    id: 'math-1-4',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: বৃত্ত',
    nameEn: 'Circles',
  },
  {
    id: 'math-1-5',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: বিন্যাস ও সমাবেশ',
    nameEn: 'Permutations and Combinations',
  },
  {
    id: 'math-1-6',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: ত্রিকোণমিতিক অনুপাত',
    nameEn: 'Trigonometric Ratios',
  },
  {
    id: 'math-1-7',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: সংযুক্ত কোণের ত্রিকোণমিতিক অনুপাত',
    nameEn: 'Trig Ratios of Associated Angles',
  },
  {
    id: 'math-1-8',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: ফাংশন ও ফাংশনের লেখচিত্র',
    nameEn: 'Functions and Graphs',
  },
  {
    id: 'math-1-9',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: অন্তরীকরণ',
    nameEn: 'Differentiation / Calculus',
  },
  {
    id: 'math-1-10',
    subject: 'higher_math' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: যোগজীকরণ',
    nameEn: 'Integration',
  },
  // ==================== HIGHER_MATH 2ND PAPER ====================
  {
    id: 'math-2-1',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: বাস্তব সংখ্যা ও অসমতা',
    nameEn: 'Real Numbers and Inequalities',
  },
  {
    id: 'math-2-2',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: যোগাশ্রয়ী প্রোগ্রাম',
    nameEn: 'Linear Programming',
  },
  {
    id: 'math-2-3',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: জটিল সংখ্যা',
    nameEn: 'Complex Numbers',
  },
  {
    id: 'math-2-4',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: বহুপদী ও বহুপদী সমীকরণ',
    nameEn: 'Polynomials and Equations',
  },
  {
    id: 'math-2-5',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: দ্বিপদী বিস্তার',
    nameEn: 'Binomial Expansion',
  },
  {
    id: 'math-2-6',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: কণিক',
    nameEn: 'Conics (Parabola, Ellipse, Hyperbola)',
  },
  {
    id: 'math-2-7',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: বিপরীত ত্রিকোণমিতিক ফাংশন ও সমীকরণ',
    nameEn: 'Inverse Trigonometric Functions',
  },
  {
    id: 'math-2-8',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: স্থিতিবিদ্যা',
    nameEn: 'Statics',
  },
  {
    id: 'math-2-9',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: সমতলে বস্তুকণার গতি',
    nameEn: 'Dynamics of Particles in a Plane',
  },
  {
    id: 'math-2-10',
    subject: 'higher_math' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: বিস্তার পরিমাপ ও সম্ভাবনা',
    nameEn: 'Measure of Dispersion and Probability',
  },
  // ==================== CHEMISTRY 1ST PAPER ====================
  {
    id: 'chem-1-1',
    subject: 'chemistry' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: ল্যাবরেটরির নিরাপদ ব্যবহার',
    nameEn: 'Safe Use of Laboratory',
  },
  {
    id: 'chem-1-2',
    subject: 'chemistry' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: গুণগত রসায়ন',
    nameEn: 'Qualitative Chemistry',
  },
  {
    id: 'chem-1-3',
    subject: 'chemistry' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: মৌলের পর্যায়বৃত্ত ধর্ম ও রাসায়নিক বন্ধন',
    nameEn: 'Periodic Properties and Chemical Bonding of Elements',
  },
  {
    id: 'chem-1-4',
    subject: 'chemistry' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: রাসায়নিক পরিবর্তন',
    nameEn: 'Chemical Changes',
  },
  {
    id: 'chem-1-5',
    subject: 'chemistry' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: কর্মমুখী রসায়ন',
    nameEn: 'Vocational/Working Chemistry',
  },
  // ==================== CHEMISTRY 2ND PAPER ====================
  {
    id: 'chem-2-1',
    subject: 'chemistry' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: পরিবেশ রসায়ন',
    nameEn: 'Environmental Chemistry',
  },
  {
    id: 'chem-2-2',
    subject: 'chemistry' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: জৈব রসায়ন',
    nameEn: 'Organic Chemistry',
  },
  {
    id: 'chem-2-3',
    subject: 'chemistry' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: পরিমাণগত রসায়ন',
    nameEn: 'Quantitative Chemistry',
  },
  {
    id: 'chem-2-4',
    subject: 'chemistry' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: তড়িৎ রসায়ন',
    nameEn: 'Electrochemistry',
  },
  {
    id: 'chem-2-5',
    subject: 'chemistry' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: অর্থনৈতিক রসায়ন',
    nameEn: 'Economic Chemistry',
  },
  // ==================== BIOLOGY 1ST PAPER ====================
  {
    id: 'bio-1-1',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: কোষ ও এর গঠন',
    nameEn: 'Cell and Its Structure',
  },
  {
    id: 'bio-1-2',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: কোষ বিভাজন',
    nameEn: 'Cell Division',
  },
  {
    id: 'bio-1-3',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: কোষ রসায়ন',
    nameEn: 'Cell Chemistry',
  },
  {
    id: 'bio-1-4',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: অণুজীব',
    nameEn: 'Microorganisms',
  },
  {
    id: 'bio-1-5',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: শৈবাল ও ছত্রাক',
    nameEn: 'Algae and Fungi',
  },
  {
    id: 'bio-1-6',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: ব্রায়োফাইটা ও টেরিডোফাইটা',
    nameEn: 'Bryophyta and Pteridophyta',
  },
  {
    id: 'bio-1-7',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: নগ্নবীজী ও আবৃতবীজী উদ্ভিদ',
    nameEn: 'Gymnosperm and Angiosperm',
  },
  {
    id: 'bio-1-8',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: টিস্যু ও টিস্যুতন্ত্র',
    nameEn: 'Tissue and Tissue System',
  },
  {
    id: 'bio-1-9',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: উদ্ভিদ শারীরতত্ত্ব',
    nameEn: 'Plant Physiology',
  },
  {
    id: 'bio-1-10',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: উদ্ভিদ প্রজনন',
    nameEn: 'Plant Reproduction',
  },
  {
    id: 'bio-1-11',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 11,
    nameBn: 'অধ্যায় ১১: জীবপ্রযুক্তি',
    nameEn: 'Biotechnology',
  },
  {
    id: 'bio-1-12',
    subject: 'biology' as SubjectId,
    paper: '1st' as PaperId,
    chapterNumber: 12,
    nameBn: 'অধ্যায় ১২: জীবের পরিবেশ বিস্তার ও সংরক্ষণ',
    nameEn: 'Environment, Extent and Conservation of Organisms',
  },
  // ==================== BIOLOGY 2ND PAPER ====================
  {
    id: 'bio-2-1',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: প্রাণীর বিভিন্নতা ও শ্রেণিবিন্যাস',
    nameEn: 'Animal Diversity and Classification',
  },
  {
    id: 'bio-2-2',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: প্রাণীর পরিচিতি: হাইড্রা, ঘাসফড়িং ও রুই মাছ',
    nameEn: 'Introduction to Animals: Hydra, Grasshopper & Rohu Fish',
  },
  {
    id: 'bio-2-3',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: পরিপাক ও শোষণ',
    nameEn: 'Digestion and Absorption',
  },
  {
    id: 'bio-2-4',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: রক্ত ও সঞ্চালন',
    nameEn: 'Blood and Circulation',
  },
  {
    id: 'bio-2-5',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: শ্বাসক্রিয়া ও শ্বসন',
    nameEn: 'Breathing and Respiration',
  },
  {
    id: 'bio-2-6',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: বর্জ্য ও নিষ্কাশন',
    nameEn: 'Excretion and Osmoregulation',
  },
  {
    id: 'bio-2-7',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: চলন ও অঙ্গচালনা',
    nameEn: 'Locomotion and Movement',
  },
  {
    id: 'bio-2-8',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: সমন্বয় ও নিয়ন্ত্রণ: স্নায়ুতন্ত্র ও হরমোন',
    nameEn: 'Coordination and Control: Nervous System & Hormones',
  },
  {
    id: 'bio-2-9',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: মানব জীবনের ধারাবাহিকতা',
    nameEn: 'Human Reproduction',
  },
  {
    id: 'bio-2-10',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: মানবদেহের প্রতিরক্ষা তন্ত্র',
    nameEn: 'Immune System',
  },
  {
    id: 'bio-2-11',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 11,
    nameBn: 'অধ্যায় ১১: জিনতত্ত্ব ও বিবর্তন',
    nameEn: 'Genetics and Evolution',
  },
  {
    id: 'bio-2-12',
    subject: 'biology' as SubjectId,
    paper: '2nd' as PaperId,
    chapterNumber: 12,
    nameBn: 'অধ্যায় ১২: প্রাণীর আচরণ',
    nameEn: 'Animal Behavior',
  },
];

export const createCleanChapter = (meta: ChapterMetadata): ChapterProgress => ({
  ...meta,
  exam1: null,
  exam2: null,
  exam3: null,
  average: null,
  isCurrentWeek: false,
  status: 'not_started',
  theoryDone: false,
  practiceDone: false,
  mcqDone: false,
  questionBankDone: false,
  notes: '',
});

export const getCleanChapters = (): ChapterProgress[] => {
  return CHAPTER_METADATA.map(createCleanChapter);
};

export const INITIAL_CHAPTERS: ChapterProgress[] = getCleanChapters();

export const INITIAL_EXAMS: AdmissionExam[] = [
  {
    id: 'ru-admission-2027',
    name: 'Rajshahi University Admission Test',
    nameBn: 'রাজশাহী বিশ্ববিদ্যালয় ভর্তি পরীক্ষা',
    shortName: 'Rajshahi University',
    targetDate: '2027-01-09T10:00:00',
    category: 'university',
    venue: 'Rajshahi University',
    isPinned: false,
  },
  {
    id: 'cu-admission-2027',
    name: 'Chittagong University Admission Test',
    nameBn: 'চট্টগ্রাম বিশ্ববিদ্যালয় ভর্তি পরীক্ষা',
    shortName: 'Chittagong University',
    targetDate: '2027-01-30T10:00:00',
    category: 'university',
    venue: 'Chittagong University',
    isPinned: false,
  },
];

export const calculateChapterAverage = (
  exam1: number | null | undefined,
  exam2: number | null | undefined,
  exam3: number | null | undefined
): number | null => {
  const hasTaken =
    (exam1 !== null && exam1 !== undefined) ||
    (exam2 !== null && exam2 !== undefined) ||
    (exam3 !== null && exam3 !== undefined);

  if (!hasTaken) {
    return null;
  }

  const s1 = typeof exam1 === 'number' ? exam1 : 0;
  const s2 = typeof exam2 === 'number' ? exam2 : 0;
  const s3 = typeof exam3 === 'number' ? exam3 : 0;

  return Math.round(((s1 + s2 + s3) / 3) * 10) / 10;
};

