import { ChapterProgress, AdmissionExam } from '../types';

export const INITIAL_CHAPTERS: ChapterProgress[] = [
  // ==================== PHYSICS 1ST PAPER ====================
  {
    id: 'phy-1-1',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: ভৌত জগত ও পরিমাপ',
    nameEn: 'Physical World and Measurement',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-1-2',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: ভেক্টর',
    nameEn: 'Vectors',
    exam1: 85,
    exam2: 78,
    exam3: null,
    average: 81.5,
    isCurrentWeek: false,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: true,
    mcqDone: true,
    questionBankDone: false,
    notes: 'Dot & Cross product mastered, river-boat problem practice needed',
  },
  {
    id: 'phy-1-3',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: গতিবিদ্যা',
    nameEn: 'Dynamics',
    exam1: 72,
    exam2: 80,
    exam3: null,
    average: 76,
    isCurrentWeek: false,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: true,
    mcqDone: false,
    questionBankDone: false,
    notes: 'Projectile motion trajectory formulas reviewed',
  },
  {
    id: 'phy-1-4',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: নিউটনীয় বলবিদ্যা',
    nameEn: 'Newtonian Mechanics',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: true,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: 'Banking of roads, moment of inertia & torque focus this week',
  },
  {
    id: 'phy-1-5',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: কাজ, শক্তি ও ক্ষমতা',
    nameEn: 'Work, Energy and Power',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-1-6',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: মহাকর্ষ ও অভিকর্ষ',
    nameEn: 'Gravitation and Gravity',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-1-7',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: পদার্থের গাঠনিক ধর্ম',
    nameEn: 'Structural Properties of Matter',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-1-8',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: পর্যায়বৃত্ত গতি',
    nameEn: 'Periodic Motion',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-1-9',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: তরঙ্গ',
    nameEn: 'Waves',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-1-10',
    subject: 'physics',
    paper: '1st',
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: আদর্শ গ্যাস ও গ্যাসের গতিতত্ত্ব',
    nameEn: 'Ideal Gas and Kinetic Theory of Gases',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },

  // ==================== PHYSICS 2ND PAPER ====================
  {
    id: 'phy-2-1',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: তাপগতিবিদ্যা',
    nameEn: 'Thermodynamics',
    exam1: 88,
    exam2: 84,
    exam3: null,
    average: 86,
    isCurrentWeek: false,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: true,
    mcqDone: true,
    questionBankDone: false,
    notes: 'Carnot engine efficiency & entropy calculations done',
  },
  {
    id: 'phy-2-2',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: স্থির তড়িৎ',
    nameEn: 'Static Electricity',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-2-3',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: চল তড়িৎ',
    nameEn: 'Current Electricity',
    exam1: 92,
    exam2: 90,
    exam3: 95,
    average: 92.3,
    isCurrentWeek: false,
    status: 'completed',
    theoryDone: true,
    practiceDone: true,
    mcqDone: true,
    questionBankDone: true,
    notes: "Kirchhoff's Laws & Wheatstone bridge problems completed",
  },
  {
    id: 'phy-2-4',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: তড়িৎ প্রবাহের চৌম্বক ক্রিয়া ও চুম্বকত্ব',
    nameEn: 'Magnetic Effects of Current & Magnetism',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-2-5',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: তাড়িতচৌম্বকীয় আবেশ ও পরিবর্তী প্রবাহ',
    nameEn: 'Electromagnetic Induction & AC',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-2-6',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: জ্যামিতিক আলোকবিজ্ঞান',
    nameEn: 'Geometrical Optics',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-2-7',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: ভৌত আলোকবিজ্ঞান',
    nameEn: 'Physical Optics',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-2-8',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: আধুনিক পদার্থবিজ্ঞানের সূচনা',
    nameEn: 'Introduction to Modern Physics',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-2-9',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: পরমাণু মডেল ও নিউক্লিয়ার পদার্থবিজ্ঞান',
    nameEn: 'Atomic Model and Nuclear Physics',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-2-10',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: সেমিকন্ডাক্টর ও ইলেকট্রনিক্স',
    nameEn: 'Semiconductors and Electronics',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'phy-2-11',
    subject: 'physics',
    paper: '2nd',
    chapterNumber: 11,
    nameBn: 'অধ্যায় ১১: জ্যোতির্বিজ্ঞান',
    nameEn: 'Astronomy',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },

  // ==================== HIGHER MATH 1ST PAPER ====================
  {
    id: 'math-1-1',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: ম্যাট্রিক্স ও নির্ণায়ক',
    nameEn: 'Matrices and Determinants',
    exam1: 95,
    exam2: 90,
    exam3: 92,
    average: 92.3,
    isCurrentWeek: false,
    status: 'completed',
    theoryDone: true,
    practiceDone: true,
    mcqDone: true,
    questionBankDone: true,
    notes: "Cramer's rule & inverse matrix inverse properties mastered",
  },
  {
    id: 'math-1-2',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: ভেক্টর',
    nameEn: 'Vectors (Math)',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-1-3',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: সরলরেখা',
    nameEn: 'Straight Lines',
    exam1: 82,
    exam2: 86,
    exam3: null,
    average: 84,
    isCurrentWeek: false,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: true,
    mcqDone: true,
    questionBankDone: false,
    notes: 'Perpendicular distance & bisector problems practiced',
  },
  {
    id: 'math-1-4',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: বৃত্ত',
    nameEn: 'Circles',
    exam1: 76,
    exam2: 82,
    exam3: null,
    average: 79,
    isCurrentWeek: false,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: true,
    mcqDone: false,
    questionBankDone: false,
    notes: 'Tangent equation through point and intersection chord',
  },
  {
    id: 'math-1-5',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: বিন্যাস ও সমাবেশ',
    nameEn: 'Permutations and Combinations',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-1-6',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: ত্রিকোণমিতিক অনুপাত',
    nameEn: 'Trigonometric Ratios',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-1-7',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: সংযুক্ত কোণের ত্রিকোণমিতিক অনুপাত',
    nameEn: 'Trig Ratios of Associated Angles',
    exam1: 80,
    exam2: 85,
    exam3: null,
    average: 82.5,
    isCurrentWeek: false,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: true,
    mcqDone: false,
    questionBankDone: false,
    notes: 'Sub-multiple angle transformations',
  },
  {
    id: 'math-1-8',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: ফাংশন ও ফাংশনের লেখচিত্র',
    nameEn: 'Functions and Graphs',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-1-9',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: অন্তরীকরণ',
    nameEn: 'Differentiation / Calculus',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: true,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: "Limits (L'Hopital rule), product & quotient rule, maxima & minima",
  },
  {
    id: 'math-1-10',
    subject: 'higher_math',
    paper: '1st',
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: যোগজীকরণ',
    nameEn: 'Integration',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },

  // ==================== HIGHER MATH 2ND PAPER ====================
  {
    id: 'math-2-1',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: বাস্তব সংখ্যা ও অসমতা',
    nameEn: 'Real Numbers and Inequalities',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-2-2',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: যোগাশ্রয়ী প্রোগ্রাম',
    nameEn: 'Linear Programming',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-2-3',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: জটিল সংখ্যা',
    nameEn: 'Complex Numbers',
    exam1: 88,
    exam2: 92,
    exam3: null,
    average: 90,
    isCurrentWeek: false,
    status: 'in_progress',
    theoryDone: true,
    practiceDone: true,
    mcqDone: true,
    questionBankDone: false,
    notes: "Cube roots of unity & De Moivre's theorem application",
  },
  {
    id: 'math-2-4',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: বহুপদী ও বহুপদী সমীকরণ',
    nameEn: 'Polynomials and Equations',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-2-5',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: দ্বিপদী বিস্তার',
    nameEn: 'Binomial Expansion',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-2-6',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: কণিক',
    nameEn: 'Conics (Parabola, Ellipse, Hyperbola)',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-2-7',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: বিপরীত ত্রিকোণমিতিক ফাংশন ও সমীকরণ',
    nameEn: 'Inverse Trigonometric Functions',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-2-8',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: স্থিতিবিদ্যা',
    nameEn: 'Statics',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: "Lami's theorem & like/unlike parallel forces",
  },
  {
    id: 'math-2-9',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: সমতলে বস্তুকণার গতি',
    nameEn: 'Dynamics of Particles in a Plane',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'math-2-10',
    subject: 'higher_math',
    paper: '2nd',
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: বিস্তার পরিমাপ ও সম্ভাবনা',
    nameEn: 'Measure of Dispersion and Probability',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },

  // ==================== CHEMISTRY 1ST PAPER ====================
  {
    id: 'chem-1-1',
    subject: 'chemistry',
    paper: '1st',
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: ল্যাবরেটরির নিরাপদ ব্যবহার',
    nameEn: 'Safe Use of Laboratory',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'chem-1-2',
    subject: 'chemistry',
    paper: '1st',
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: গুণগত রসায়ন',
    nameEn: 'Qualitative Chemistry',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'chem-1-3',
    subject: 'chemistry',
    paper: '1st',
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: মৌলের পর্যায়বৃত্ত ধর্ম ও রাসায়নিক বন্ধন',
    nameEn: 'Periodic Properties and Chemical Bonding of Elements',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'chem-1-4',
    subject: 'chemistry',
    paper: '1st',
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: রাসায়নিক পরিবর্তন',
    nameEn: 'Chemical Changes',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'chem-1-5',
    subject: 'chemistry',
    paper: '1st',
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: কর্মমুখী রসায়ন',
    nameEn: 'Vocational/Working Chemistry',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },

  // ==================== CHEMISTRY 2ND PAPER ====================
  {
    id: 'chem-2-1',
    subject: 'chemistry',
    paper: '2nd',
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: পরিবেশ রসায়ন',
    nameEn: 'Environmental Chemistry',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'chem-2-2',
    subject: 'chemistry',
    paper: '2nd',
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: জৈব রসায়ন',
    nameEn: 'Organic Chemistry',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'chem-2-3',
    subject: 'chemistry',
    paper: '2nd',
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: পরিমাণগত রসায়ন',
    nameEn: 'Quantitative Chemistry',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'chem-2-4',
    subject: 'chemistry',
    paper: '2nd',
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: তড়িৎ রসায়ন',
    nameEn: 'Electrochemistry',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'chem-2-5',
    subject: 'chemistry',
    paper: '2nd',
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: অর্থনৈতিক রসায়ন',
    nameEn: 'Economic Chemistry',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },

  // ==================== BIOLOGY 1ST PAPER (BOTANY) ====================
  {
    id: 'bio-1-1',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: কোষ ও এর গঠন',
    nameEn: 'Cell and Its Structure',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-2',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: কোষ বিভাজন',
    nameEn: 'Cell Division',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-3',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: কোষ রসায়ন',
    nameEn: 'Cell Chemistry',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-4',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: অণুজীব',
    nameEn: 'Microorganisms',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-5',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: শৈবাল ও ছত্রাক',
    nameEn: 'Algae and Fungi',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-6',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: ব্রায়োফাইটা ও টেরিডোফাইটা',
    nameEn: 'Bryophyta and Pteridophyta',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-7',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: নগ্নবীজী ও আবৃতবীজী উদ্ভিদ',
    nameEn: 'Gymnosperm and Angiosperm',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-8',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: টিস্যু ও টিস্যুতন্ত্র',
    nameEn: 'Tissue and Tissue System',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-9',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: উদ্ভিদ শারীরতত্ত্ব',
    nameEn: 'Plant Physiology',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-10',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: উদ্ভিদ প্রজনন',
    nameEn: 'Plant Reproduction',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-11',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 11,
    nameBn: 'অধ্যায় ১১: জীবপ্রযুক্তি',
    nameEn: 'Biotechnology',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-1-12',
    subject: 'biology',
    paper: '1st',
    chapterNumber: 12,
    nameBn: 'অধ্যায় ১২: জীবের পরিবেশ বিস্তার ও সংরক্ষণ',
    nameEn: 'Environment, Extent and Conservation of Organisms',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },

  // ==================== BIOLOGY 2ND PAPER (ZOOLOGY) ====================
  {
    id: 'bio-2-1',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 1,
    nameBn: 'অধ্যায় ১: প্রাণীর বিভিন্নতা ও শ্রেণিবিন্যাস',
    nameEn: 'Animal Diversity and Classification',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-2',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 2,
    nameBn: 'অধ্যায় ২: প্রাণীর পরিচিতি: হাইড্রা, ঘাসফড়িং ও রুই মাছ',
    nameEn: 'Introduction to Animals: Hydra, Grasshopper & Rohu Fish',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-3',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 3,
    nameBn: 'অধ্যায় ৩: পরিপাক ও শোষণ',
    nameEn: 'Digestion and Absorption',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-4',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 4,
    nameBn: 'অধ্যায় ৪: রক্ত ও সঞ্চালন',
    nameEn: 'Blood and Circulation',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-5',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 5,
    nameBn: 'অধ্যায় ৫: শ্বাসক্রিয়া ও শ্বসন',
    nameEn: 'Breathing and Respiration',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-6',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 6,
    nameBn: 'অধ্যায় ৬: বর্জ্য ও নিষ্কাশন',
    nameEn: 'Excretion and Osmoregulation',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-7',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 7,
    nameBn: 'অধ্যায় ৭: চলন ও অঙ্গচালনা',
    nameEn: 'Locomotion and Movement',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-8',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 8,
    nameBn: 'অধ্যায় ৮: সমন্বয় ও নিয়ন্ত্রণ: স্নায়ুতন্ত্র ও হরমোন',
    nameEn: 'Coordination and Control: Nervous System & Hormones',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-9',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 9,
    nameBn: 'অধ্যায় ৯: মানব জীবনের ধারাবাহিকতা',
    nameEn: 'Human Reproduction',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-10',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 10,
    nameBn: 'অধ্যায় ১০: মানবদেহের প্রতিরক্ষা তন্ত্র',
    nameEn: 'Immune System',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-11',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 11,
    nameBn: 'অধ্যায় ১১: জিনতত্ত্ব ও বিবর্তন',
    nameEn: 'Genetics and Evolution',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
  {
    id: 'bio-2-12',
    subject: 'biology',
    paper: '2nd',
    chapterNumber: 12,
    nameBn: 'অধ্যায় ১২: প্রাণীর আচরণ',
    nameEn: 'Animal Behavior',
    exam1: null,
    exam2: null,
    exam3: null,
    average: null,
    isCurrentWeek: false,
    status: 'not_started',
    theoryDone: false,
    practiceDone: false,
    mcqDone: false,
    questionBankDone: false,
    notes: '',
  },
];

export const INITIAL_EXAMS: AdmissionExam[] = [
  {
    id: 'buet-2026',
    name: 'BUET Admission Test',
    nameBn: 'বুয়েট ভর্তি পরীক্ষা',
    shortName: 'BUET',
    targetDate: '2026-11-28T10:00:00',
    category: 'engineering',
    venue: 'BUET Campus, Dhaka',
    isPinned: true,
  },
  {
    id: 'du-ka-2026',
    name: "Dhaka University 'A' Unit (Science)",
    nameBn: "ঢাকা বিশ্ববিদ্যালয় 'ক' ইউনিট",
    shortName: "DU 'A' Unit",
    targetDate: '2026-12-05T11:00:00',
    category: 'university',
    venue: 'Divisional Exam Centers',
    isPinned: true,
  },
  {
    id: 'ckruet-2026',
    name: 'CKRUET Combined Engineering (CUET, KUET, RUET)',
    nameBn: 'প্রকৌশল গুচ্ছ ভর্তি পরীক্ষা',
    shortName: 'CKRUET',
    targetDate: '2026-12-19T10:00:00',
    category: 'engineering',
    venue: 'CUET / KUET / RUET Campuses',
    isPinned: true,
  },
  {
    id: 'gst-2026',
    name: 'GST General & Science-Technology Combined (A Unit)',
    nameBn: 'জিএসটি গুচ্ছ বিজ্ঞান',
    shortName: 'GST Science',
    targetDate: '2027-01-09T11:00:00',
    category: 'university',
    venue: 'Designated University Centers',
    isPinned: false,
  },
  {
    id: 'medical-2026',
    name: 'MBBS Medical Admission Test',
    nameBn: 'মেডিকেল ভর্তি পরীক্ষা',
    shortName: 'Medical (MBBS)',
    targetDate: '2026-11-14T10:00:00',
    category: 'medical',
    venue: 'DGHS Medical Test Centers',
    isPinned: false,
  },
];
